import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Chief Technology Officer",
    company: "Lummy Ticket",
    logo: "/images/placeholder.webp",
    location: "Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Full-time",
    start_date: "2025-04",
    end_date: null,
    industry: "Web3 / Ticketing",
    link: "https://lummyticket.com",
    responsibilities: [
      "Led end-to-end product development of an NFT-based ticketing platform on the Lisk blockchain.",
      "Managed a team of 4 members under technical direction while defining the product roadmap and feature priorities.",
      "Coordinated weekly team meetings, sprint planning, and ensured deliverables aligned with project timeline.",
    ],
    lessons_learned: [
      "Bridged business strategy and engineering execution as a founder/CTO.",
      "Operated within a Web3 incubator program with formal milestones and deliverables.",
    ],
    impact: [
      "Completed the Lisk Spark Incubator (Indonesia's 1st government-backed Web3 incubator) and secured USD 4,600 in grant funding.",
      "Won Top 5 of the Lisk Builders Challenge: Round One and the Social Media Challenge.",
    ],
    isShow: true,
  },
  {
    position: "Freelance Product Developer & Consultant",
    company: "Self-employed",
    logo: "/images/placeholder.webp",
    location: "Singapore-based clients 🇸🇬",
    location_type: "Remote",
    type: "Freelance",
    start_date: "2025-03",
    end_date: null,
    industry: "Product Development",
    link: null,
    responsibilities: [
      "Acting as Product Manager and sole developer, delivering 6 business automation websites and 5 company profiles.",
      "Leading product discovery sessions, brainstorming with clients, and designing feature sets before development.",
      "Advising on technical feasibility and shaping product direction as the decision-maker bridging business needs and technical execution.",
    ],
    lessons_learned: [
      "Managed full project lifecycle independently — requirement gathering through deployment.",
      "Sharpened ability to translate business processes into product requirements.",
    ],
    impact: [
      "Delivered 11+ client projects across diverse industries.",
      "Established trust with Singapore-based clients via consistent end-to-end delivery.",
    ],
    isShow: true,
  },
  {
    position: "Full Stack Developer",
    company: "PT Zegen Solusi Mandiri",
    logo: "/images/placeholder.webp",
    location: "Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Full-time",
    start_date: "2025-02",
    end_date: "2026-02",
    industry: "EdTech / LMS",
    link: null,
    responsibilities: [
      "Collaborated with a cross-functional team to develop a comprehensive Learning Management System using React, Golang, and Chakra UI.",
      "Built 10+ prototype mini-projects to validate core LMS features before production implementation.",
      "Used the LMS project as foundation for undergraduate thesis research, bridging practical development with academic objectives.",
    ],
    lessons_learned: [
      "Strengthened full-stack skills across React frontend and Golang backend.",
      "Practiced design-system thinking with Chakra UI in a production codebase.",
    ],
    impact: [
      "Helped ship a working LMS that became the basis of a published undergraduate thesis.",
    ],
    isShow: true,
  },
  {
    position: "SEO Backlinking Specialist",
    company: "PT Laskar Digital Indonesia",
    logo: "/images/placeholder.webp",
    location: "Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Part-time",
    start_date: "2021-09",
    end_date: "2021-12",
    industry: "Digital Marketing",
    link: null,
    responsibilities: [
      "Contributed to ranking 40+ websites/articles on Google's first page for targeted keywords through coordinated SEO team efforts.",
      "Published 174 SEO-optimized articles and curated 150 high-authority social bookmarking websites.",
      "Used WordPress, SEOquake, Google Analytics, and Search Console to track performance and optimize results.",
    ],
    lessons_learned: [
      "Hands-on understanding of how on-page and off-page SEO converts to ranking outcomes.",
    ],
    impact: [
      "Helped move 40+ pages onto the first Google SERP for prioritized keywords.",
    ],
    isShow: true,
  },
  {
    position: "FILE / Filemagz Manager",
    company: "Bina Nusantara Computer Club (BNCC)",
    logo: "/images/placeholder.webp",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Hybrid",
    type: "Part-time",
    start_date: "2024-01",
    end_date: "2025-01",
    industry: "Student Organization",
    link: "https://bncc.net/",
    responsibilities: [
      "Led a team of 6, managing content strategy through monthly sprints across @filemagz and @filetechno.",
      "Mentored 32 activists in content creation and video editing.",
      "Established 10+ partnerships with organizations including CTI Group, CakeResume, ToffeDev, and DevOpsDays Jakarta 2024.",
    ],
    lessons_learned: [
      "Managed cross-functional creative teams with sprint cadence and feedback loops.",
    ],
    impact: [
      "Grew followers by +2,600 across @filemagz and @filetechno.",
      "Drove record-breaking engagement: 18,000 likes on top reel, 280,000 views, 170,000 TikTok views.",
    ],
    isShow: true,
  },
  {
    position: "Head of Social Media",
    company: "MarshaOshi",
    logo: "/images/placeholder.webp",
    location: "Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Part-time",
    start_date: "2020-12",
    end_date: "2023-01",
    industry: "Entertainment / Fanbase",
    link: null,
    responsibilities: [
      "Led the social media team across Twitter/X, Instagram, TikTok, and Showroom Live.",
      "Owned content strategy and posting cadence across platforms.",
    ],
    lessons_learned: [
      "Built communities from zero, with a feel for what resonates per platform.",
    ],
    impact: [
      "Grew Twitter/X from 700 to 7K followers, Instagram 0 → 1.8K, TikTok 0 → 1.6K.",
      "Averaged 527,000 tweet impressions per month during the last 5 months of tenure.",
    ],
    isShow: true,
  },
];
