import {
  BsGithub as GithubIcon,
  BsInstagram as InstagramIcon,
  BsLinkedin as LinkedinIcon,
  BsTelegram as TelegramIcon,
  BsTiktok as TiktokIcon,
  BsTwitterX as TwitterIcon,
  BsWhatsapp as WhatsappIcon,
} from "react-icons/bs";
import { SiGmail } from "react-icons/si";

import { SocialMediaProps } from "../types/socialMedia";

const iconSize = 35;
const backgroundIconSize = 256;

export const SOCIAL_MEDIA: SocialMediaProps[] = [
  {
    name: "gmail",
    href: "mailto:luthfihadi543@gmail.com",
    icon: <SiGmail size={iconSize} />,
    backgroundIcon: <SiGmail size={backgroundIconSize} />,
    textColor: "text-red-300",
    backgroundColor: "bg-red-300",
    borderColor: "border-red-300",
    backgroundGradientColor: "bg-gradient-to-b from-red-700 to-red-900",
    isShow: true,
  },
  {
    name: "whatsapp",
    href: "https://wa.me/6281295603317",
    icon: <WhatsappIcon size={iconSize} />,
    backgroundIcon: <WhatsappIcon size={backgroundIconSize} />,
    textColor: "text-green-200",
    backgroundColor: "bg-green-200",
    borderColor: "border-green-200",
    backgroundGradientColor: "bg-gradient-to-b from-green-700 to-green-900",
    isShow: true,
  },
  {
    name: "github",
    href: "https://github.com/luthfidi",
    icon: <GithubIcon size={iconSize} />,
    backgroundIcon: <GithubIcon size={backgroundIconSize} />,
    textColor: "text-slate-400",
    backgroundColor: "bg-slate-400",
    borderColor: "border-slate-400",
    backgroundGradientColor: "bg-gradient-to-b from-slate-900 to-slate-950",
    isShow: true,
  },
  {
    name: "linkedin",
    href: "https://www.linkedin.com/in/luthfi-hadi",
    icon: <LinkedinIcon size={iconSize} />,
    backgroundIcon: <LinkedinIcon size={backgroundIconSize} />,
    textColor: "text-sky-300",
    backgroundColor: "bg-sky-300",
    borderColor: "border-sky-300",
    backgroundGradientColor: "bg-gradient-to-b from-sky-700 to-sky-900",
    isShow: true,
  },
  {
    name: "instagram",
    href: "https://www.instagram.com/luthfidi_/",
    icon: <InstagramIcon size={iconSize} />,
    backgroundIcon: <InstagramIcon size={backgroundIconSize} />,
    textColor: "text-purple-200",
    backgroundColor: "bg-purple-200",
    borderColor: "border-purple-200",
    backgroundGradientColor:
      "bg-gradient-to-b from-purple-700 via-pink-500 to-orange-500",
    isShow: true,
  },
  {
    name: "tiktok",
    href: "https://www.tiktok.com/@anordinarycat",
    icon: <TiktokIcon size={iconSize} />,
    backgroundIcon: <TiktokIcon size={backgroundIconSize} />,
    textColor: "text-neutral-400",
    backgroundColor: "bg-neutral-400",
    borderColor: "border-neutral-400",
    backgroundGradientColor: "bg-gradient-to-b from-neutral-700 to-neutral-900",
    isShow: true,
  },
  {
    name: "twitter",
    href: "https://x.com/0xluthfidi",
    icon: <TwitterIcon size={iconSize} />,
    backgroundIcon: <TwitterIcon size={backgroundIconSize} />,
    textColor: "text-zinc-300",
    backgroundColor: "bg-zinc-300",
    borderColor: "border-zinc-300",
    backgroundGradientColor: "bg-gradient-to-b from-zinc-800 to-black",
    isShow: true,
  },
  {
    name: "telegram",
    href: "https://t.me/filonami",
    icon: <TelegramIcon size={iconSize} />,
    backgroundIcon: <TelegramIcon size={backgroundIconSize} />,
    textColor: "text-cyan-200",
    backgroundColor: "bg-cyan-200",
    borderColor: "border-cyan-200",
    backgroundGradientColor: "bg-gradient-to-b from-cyan-700 to-cyan-900",
    isShow: true,
  },
];
